import type { Metadata } from "next";
import "./globals.css";
import { usePathname } from 'next/navigation';
import Header from '@/components/header/header';
import { Provider } from "react-redux";
import store from "@/store/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <Provider store={store}>
      <html lang="ru">
        <body>
          {pathname !== '/register' && <Header />}
          {children}
          <div id="modal-root"></div>
        </body>
      </html>
    </Provider>
  );
}
