import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";
import ClientHeader from '@/components/header/client-header'; // Импорт клиентского компонента

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="ru">
        <body>
          <ClientHeader />
          {children}
          <div id="modal-root"></div>
        </body>
      </html>
    </Provider>
  );
}
